/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BrushDip (https://sketchfab.com/BrushDip)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-computer-sketchfab-weekly-11-mar23-d9931a9aba7c4ea1bc12b2a59dcef16e
Title: 3d computer  - Sketchfab Weekly - 11 Mar'23
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap'; 

const DemoComputer=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    '/models/DemoComputer.glb'
  )
  const txt=useVideoTexture(props.texture?props.texture:'/textures/project/project1.mp4')
  useEffect(()=>{
    if(txt){
        txt.flipY=false
    }
  },[txt])
  useGSAP(()=>{
    gsap.from(group.current.rotation,{
        y:Math.PI,
        duration:1,
        ease:'power3.out'
    })
  },[txt])

  return (
    <group key={props.texture} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0.033]}>
          <group
            name="4cef7c9d510940d8bf5a9a57aa408b42fbx"
            rotation={[-Math.PI, 0, 0]}
            scale={0.015}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Monitor-A-"
                  position={[5.993, -1.311, 0.887]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.922, 1, 0.858]}>
                  <mesh
                    name="Monitor-A-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Monitor-A-_computer_0'].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Monitor-B-"
                  position={[5.993, -0.946, 0.887]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.94, 1.019, 1.019]}>
                  <mesh
                    name="Monitor-B-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Monitor-B-_computer_0'].geometry}
                    material={materials.computer}
                  />
                </group>
                <group name="screen_glass" position={[5.923, 0.01, 0.887]} scale={[0.922, 1, 1]}>
                  <mesh
                    name="screen_glass_screen_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.screen_glass_screen_0.geometry}
                    >
                    <meshBasicMaterial map={txt}/>
                    </mesh>
                </group>
                <group
                  name="Box002"
                  position={[7.197, -10.437, -20.778]}
                  rotation={[0.092, 0, 0]}
                  scale={[1.199, 1, 1]}>
                  <mesh
                    name="Box002_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Box002_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower"
                  position={[5.991, 15.639, -21.506]}
                  scale={[1.264, 3.46, 3.388]}>
                  <mesh
                    name="Tower_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tower_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="tower-case"
                  position={[5.991, 15.06, -22.123]}
                  scale={[0.229, 4.055, 4.842]}>
                  <mesh
                    name="tower-case_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['tower-case_computer_0'].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-Front"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-Front_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-Front_computer_0'].geometry}
                    material={materials.computer}
                  />
                </group>
                <group name="base" position={[8.444, 11.264, -21.436]} scale={[1, 1.108, 1]}>
                  <mesh
                    name="base__0"
                    castShadow
                    receiveShadow
                    geometry={nodes.base__0.geometry}
                    material={materials.base__0}
                  />
                </group>
                <group
                  name="key"
                  position={[-4.63, -8.141, -18.599]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}>
                  <mesh
                    name="key_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.key_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="key-alt"
                  position={[-13.19, -8.141, -18.599]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}>
                  <mesh
                    name="key-alt_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['key-alt_computer_0'].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="key-alt-2"
                  position={[-13.19, -8.141, -18.599]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}>
                  <mesh
                    name="key-alt-2_keys_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['key-alt-2_keys_0'].geometry}
                    material={materials.keys}
                  />
                </group>
                <group
                  name="key-alt-3"
                  position={[-13.19, -8.141, -18.599]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}>
                  <mesh
                    name="key-alt-3_keys2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['key-alt-3_keys2_0'].geometry}
                    material={materials.keys2}
                  />
                </group>
                <group
                  name="mouse"
                  position={[-20.18, -10.437, -20.778]}
                  rotation={[0.092, 0, 0]}
                  scale={[1.199, 1, 1]}>
                  <mesh
                    name="mouse_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.mouse_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="mouse-wheel"
                  position={[-20.18, -10.437, -20.778]}
                  rotation={[0.092, 0, 0]}
                  scale={[1.199, 1, 1]}>
                  <mesh
                    name="mouse-wheel_keys_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['mouse-wheel_keys_0'].geometry}
                    material={materials.keys}
                  />
                </group>
                <group
                  name="Tower-light-001"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-001_Material_34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-001_Material_34_0'].geometry}
                    material={materials.Material_34}
                  />
                </group>
                <group
                  name="Tower-light-002"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-002_Material_35_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-002_Material_35_0'].geometry}
                    material={materials.Material_35}
                  />
                </group>
                <group
                  name="Tower-light-003"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-003_Material_36_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-003_Material_36_0'].geometry}
                    material={materials.Material_36}
                  />
                </group>
                <group
                  name="Tower-light-004"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-004_Material_37_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-004_Material_37_0'].geometry}
                    material={materials.Material_37}
                  />
                </group>
                <group
                  name="Tower-light-005"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-005_Material_34_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-005_Material_34_0'].geometry}
                    material={materials.Material_34}
                  />
                </group>
                <group
                  name="Tower-light-006"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-006_Material_35_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-006_Material_35_0'].geometry}
                    material={materials.Material_35}
                  />
                </group>
                <group
                  name="Tower-light-007"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-007_Material_36_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-007_Material_36_0'].geometry}
                    material={materials.Material_36}
                  />
                </group>
                <group
                  name="Tower-light-008"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}>
                  <mesh
                    name="Tower-light-008_Material_37_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Tower-light-008_Material_37_0'].geometry}
                    material={materials.Material_37}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/DemoComputer.glb')
export default DemoComputer
